apiVersion: v1
kind: PersistentVolume
metadata:
  name: itsf-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/mitra/devops-test/hello-itsf" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itsf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

